In [82]:
ascii_dict = {}
for i in range(128):
    ascii_dict[chr(i)] = i
print(ascii_dict)


{'\x00': 0, '\x01': 1, '\x02': 2, '\x03': 3, '\x04': 4, '\x05': 5, '\x06': 6, '\x07': 7, '\x08': 8, '\t': 9, '\n': 10, '\x0b': 11, '\x0c': 12, '\r': 13, '\x0e': 14, '\x0f': 15, '\x10': 16, '\x11': 17, '\x12': 18, '\x13': 19, '\x14': 20, '\x15': 21, '\x16': 22, '\x17': 23, '\x18': 24, '\x19': 25, '\x1a': 26, '\x1b': 27, '\x1c': 28, '\x1d': 29, '\x1e': 30, '\x1f': 31, ' ': 32, '!': 33, '"': 34, '#': 35, '$': 36, '%': 37, '&': 38, "'": 39, '(': 40, ')': 41, '*': 42, '+': 43, ',': 44, '-': 45, '.': 46, '/': 47, '0': 48, '1': 49, '2': 50, '3': 51, '4': 52, '5': 53, '6': 54, '7': 55, '8': 56, '9': 57, ':': 58, ';': 59, '<': 60, '=': 61, '>': 62, '?': 63, '@': 64, 'A': 65, 'B': 66, 'C': 67, 'D': 68, 'E': 69, 'F': 70, 'G': 71, 'H': 72, 'I': 73, 'J': 74, 'K': 75, 'L': 76, 'M': 77, 'N': 78, 'O': 79, 'P': 80, 'Q': 81, 'R': 82, 'S': 83, 'T': 84, 'U': 85, 'V': 86, 'W': 87, 'X': 88, 'Y': 89, 'Z': 90, '[': 91, '\\': 92, ']': 93, '^': 94, '_': 95, '`': 96, 'a': 97, 'b': 98, 'c': 99, 'd': 100, 'e': 101

In [83]:
characters = {' ': 32, '!': 33, '"': 34, '#': 35, '$': 36, '%': 37, '&': 38, "'": 39, '(': 40, ')': 41, '*': 42, '+': 43, ',': 44, '-': 45, '.': 46, '/': 47, '0': 48, '1': 49, '2': 50, '3': 51, '4': 52, '5': 53, '6': 54, '7': 55, '8': 56, '9': 57, ':': 58, ';': 59, '<': 60, '=': 61, '>': 62, '?': 63, '@': 64, 'A': 65, 'B': 66, 'C': 67, 'D': 68, 'E': 69, 'F': 70, 'G': 71, 'H': 72, 'I': 73, 'J': 74, 'K': 75, 'L': 76, 'M': 77, 'N': 78, 'O': 79, 'P': 80, 'Q': 81, 'R': 82, 'S': 83, 'T': 84, 'U': 85, 'V': 86, 'W': 87, 'X': 88, 'Y': 89, 'Z': 90, '[': 91, '\\': 92, ']': 93, '^': 94, '_': 95, '`': 96, 'a': 97, 'b': 98, 'c': 99, 'd': 100, 'e': 101, 'f': 102, 'g': 103, 'h': 104, 'i': 105, 'j': 106, 'k': 107, 'l': 108, 'm': 109, 'n': 110, 'o': 111, 'p': 112, 'q': 113, 'r': 114, 's': 115, 't': 116, 'u': 117, 'v': 118, 'w': 119, 'x': 120, 'y': 121, 'z': 122, '{': 123, '|': 124, '}': 125, '~': 126}
for key in characters:
    characters[key] -= 32
print(characters)

{' ': 0, '!': 1, '"': 2, '#': 3, '$': 4, '%': 5, '&': 6, "'": 7, '(': 8, ')': 9, '*': 10, '+': 11, ',': 12, '-': 13, '.': 14, '/': 15, '0': 16, '1': 17, '2': 18, '3': 19, '4': 20, '5': 21, '6': 22, '7': 23, '8': 24, '9': 25, ':': 26, ';': 27, '<': 28, '=': 29, '>': 30, '?': 31, '@': 32, 'A': 33, 'B': 34, 'C': 35, 'D': 36, 'E': 37, 'F': 38, 'G': 39, 'H': 40, 'I': 41, 'J': 42, 'K': 43, 'L': 44, 'M': 45, 'N': 46, 'O': 47, 'P': 48, 'Q': 49, 'R': 50, 'S': 51, 'T': 52, 'U': 53, 'V': 54, 'W': 55, 'X': 56, 'Y': 57, 'Z': 58, '[': 59, '\\': 60, ']': 61, '^': 62, '_': 63, '`': 64, 'a': 65, 'b': 66, 'c': 67, 'd': 68, 'e': 69, 'f': 70, 'g': 71, 'h': 72, 'i': 73, 'j': 74, 'k': 75, 'l': 76, 'm': 77, 'n': 78, 'o': 79, 'p': 80, 'q': 81, 'r': 82, 's': 83, 't': 84, 'u': 85, 'v': 86, 'w': 87, 'x': 88, 'y': 89, 'z': 90, '{': 91, '|': 92, '}': 93, '~': 94}


In [84]:
txt = "dfsjnSDsF NSDfs"
import math
row = math.ceil(len(txt)/3)

In [85]:
txt_matrix = []
for i in range(row):
    txt_matrix.append(list(txt[i*3:(i+1)*3]))

print(txt_matrix)

[['d', 'f', 's'], ['j', 'n', 'S'], ['D', 's', 'F'], [' ', 'N', 'S'], ['D', 'f', 's']]


In [86]:
for i in range(row):
    for j in range(3):
        txt_matrix[i][j] = characters[txt_matrix[i][j]]
print(txt_matrix)

[[68, 70, 83], [74, 78, 51], [36, 83, 38], [0, 46, 51], [36, 70, 83]]


In [87]:
import numpy as np
key = [[1,2,3],[2,2,0],[0,2,3]]
key_matrix = np.array(key, dtype=float)
txt_matrix = np.array(txt_matrix, dtype=float)

In [88]:
encrypted_matrix = txt_matrix @ key_matrix
print(encrypted_matrix)
for i in range(row):
    for j in range(3):
        encrypted_matrix[i][j] = encrypted_matrix[i][j]%95
print(encrypted_matrix)

[[208. 442. 453.]
 [230. 406. 375.]
 [202. 314. 222.]
 [ 92. 194. 153.]
 [176. 378. 357.]]
[[18. 62. 73.]
 [40. 26. 90.]
 [12. 29. 32.]
 [92.  4. 58.]
 [81. 93. 72.]]


In [89]:
reversed_characters = {}
for key, val in characters.items():
    reversed_characters[val] = key
encrypted_matrix=(encrypted_matrix.astype(int))
str_encrypted_matrix = np.array(encrypted_matrix,dtype=str)
for i in range(row):
    for j in range(3):
        str_encrypted_matrix[i][j] = reversed_characters[encrypted_matrix[i][j]]
        
print(str_encrypted_matrix)

[['2' '^' 'i']
 ['H' ':' 'z']
 [',' '=' '@']
 ['|' '$' 'Z']
 ['q' '}' 'h']]


In [90]:
encrypted_txt = []
for j in range(row):
    for k in range(3):            
        encrypted_txt.append(str_encrypted_matrix[j][k])
print(encrypted_txt)

['2', '^', 'i', 'H', ':', 'z', ',', '=', '@', '|', '$', 'Z', 'q', '}', 'h']


In [91]:
encrypted_string = ''.join(encrypted_txt)
encrypted_string

'2^iH:z,=@|$Zq}h'

In [92]:
def Encryptor(Key,Text):
    characters = {}
    for i in range(32,127):
        characters[chr(i)] = i-32
    
    while len(Text) % 3 != 0:
        Text += ' '
    import math
    row = math.ceil(len(Text)/3)
    txt_matrix = []
    for i in range(row):
        txt_matrix.append(list(Text[i*3:(i+1)*3]))
    for i in range(row):
        for j in range(3):
            txt_matrix[i][j] = characters[txt_matrix[i][j]]
    import numpy as np
    key_matrix = np.array(Key, dtype=float)
    txt_matrix = np.array(txt_matrix, dtype=float)
    encrypted_matrix = txt_matrix @ key_matrix
    for i in range(row):
        for j in range(3):
            encrypted_matrix[i][j] = encrypted_matrix[i][j]%95
    reversed_characters = {}
    for key, val in characters.items():
        reversed_characters[val] = key
    encrypted_matrix=(encrypted_matrix.astype(int))
    str_encrypted_matrix = np.array(encrypted_matrix,dtype=str)
    for i in range(row):
        for j in range(3):
            str_encrypted_matrix[i][j] = reversed_characters[encrypted_matrix[i][j]]
    encrypted_txt = []
    for j in range(row):
        for k in range(3):            
            encrypted_txt.append(str_encrypted_matrix[j][k])
    encrypted_string = ''.join(encrypted_txt)
    return encrypted_string

In [93]:
Encryptor([[1,2,3],[2,2,0],[0,2,3]],"dfsjnSDsF NSDfsa")

'2^iH:z,=@|$Zq}haC%'

In [94]:
Encryptor([[1,0,-1],[-1,0.5,1],[0.666,-0.333,-0.333]],"2^iH:z,=@|$Zq}haC%")

'$&3inS$#&?mrC6sA/_'

In [95]:
from sympy import Matrix
from sympy import mod_inverse
import numpy as np

Key = [[1,2,3],[2,2,0],[0,2,3]]
detmod = np.linalg.det(Key)%95
modular_inverse = mod_inverse(int(detmod), 95)
Key = Matrix(Key)
adj_matrix = Key.adjugate()%95
print(adj_matrix)
print(modular_inverse)
inverse_key = modular_inverse*adj_matrix%95
inverse_key = np.array(c,dtype=int)

Matrix([[6, 0, 89], [89, 3, 6], [4, 93, 93]])
16


In [96]:
Encryptor(inverse_key,"2^iH:z,=@|$Zq}haC%")

'dfsjnSDsF NSDfsa  '

In [97]:
def Decryptor(Key,Text):
    characters = {}
    for i in range(32,127):
        characters[chr(i)] = i-32
    import math
    row = math.ceil(len(Text)/3)
    txt_matrix = []
    for i in range(row):
        txt_matrix.append(list(Text[i*3:(i+1)*3]))
    for i in range(row):
        for j in range(3):
            txt_matrix[i][j] = characters[txt_matrix[i][j]]   
    from sympy import Matrix
    from sympy import mod_inverse
    import numpy as np
    detmod = np.linalg.det(Key)%95
    modular_inverse = mod_inverse(int(detmod), 95)
    Key = Matrix(Key)
    adj_matrix = Key.adjugate()%95
    inverse_key = modular_inverse*adj_matrix%95
    key_matrix = np.array(inverse_key, dtype=float)
    txt_matrix = np.array(txt_matrix, dtype=float)
    encrypted_matrix = txt_matrix @ key_matrix
    for i in range(row):
        for j in range(3):
            encrypted_matrix[i][j] = encrypted_matrix[i][j]%95
    reversed_characters = {}
    for key, val in characters.items():
        reversed_characters[val] = key
    encrypted_matrix=(encrypted_matrix.astype(int))
    str_encrypted_matrix = np.array(encrypted_matrix,dtype=str)
    for i in range(row):
        for j in range(3):
            str_encrypted_matrix[i][j] = reversed_characters[encrypted_matrix[i][j]]
    encrypted_txt = []
    for j in range(row):
        for k in range(3):            
            encrypted_txt.append(str_encrypted_matrix[j][k])
    encrypted_string = ''.join(encrypted_txt).rstrip()
    return encrypted_string

In [98]:
Decryptor([[1,2,3],[2,2,0],[0,2,3]],"2^iH:z,=@|$Zq}haC%")

'dfsjnSDsF NSDfsa'

In [99]:
#Key_inverse_check
#from sympy import Matrix
#from sympy import mod_inverse
#import numpy as np
#detmod = np.linalg.det(Key)%95
#if detmod ==0:
#    return ("Choosen Key is not invertable!")

In [100]:
def Encryptor(Key,Text):
    from sympy import Matrix
    from sympy import mod_inverse
    import numpy as np
    import math
    detmod = np.linalg.det(Key)%95
    if detmod ==0:
        return ("Choosen Key is not invertable!")    
    characters = {}
    for i in range(32,127):
        characters[chr(i)] = i-32
    
    while len(Text) % 3 != 0:
        Text += ' '
    row = math.ceil(len(Text)/3)
    txt_matrix = []
    for i in range(row):
        txt_matrix.append(list(Text[i*3:(i+1)*3]))
    for i in range(row):
        for j in range(3):
            txt_matrix[i][j] = characters[txt_matrix[i][j]]
    key_matrix = np.array(Key, dtype=float)
    txt_matrix = np.array(txt_matrix, dtype=float)
    encrypted_matrix = txt_matrix @ key_matrix
    for i in range(row):
        for j in range(3):
            encrypted_matrix[i][j] = encrypted_matrix[i][j]%95
    reversed_characters = {}
    for key, val in characters.items():
        reversed_characters[val] = key
    encrypted_matrix=(encrypted_matrix.astype(int))
    str_encrypted_matrix = np.array(encrypted_matrix,dtype=str)
    for i in range(row):
        for j in range(3):
            str_encrypted_matrix[i][j] = reversed_characters[encrypted_matrix[i][j]]
    encrypted_txt = []
    for j in range(row):
        for k in range(3):            
            encrypted_txt.append(str_encrypted_matrix[j][k])
    encrypted_string = ''.join(encrypted_txt)
    return encrypted_string

In [101]:
Encryptor([[1,0,0],[2,0,0],[0,2,3]],"dfsjnSDsF NSDfsa")

'Choosen Key is not invertable!'